import Head from 'next/head';

interface Props {
  children: React.ReactNode;
}

export default function Index({ children }: Props): JSX.Element {
  return (
    <>
      <Head>
        <title>RWA Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header></header>
      <main>
        {children}
      </main>
      <footer></footer>
    </>
  );
}

